[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Beam"

[font]
builtin_box_drawing = true
size = 14.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
