#!/bin/bash

max=`cat /sys/class/backlight/intel_backlight/max_brightness`
val=`cat /sys/class/backlight/intel_backlight/brightness`
dir=$1

# Set the default brightness value
default_brightness=500

ten_percent=$(($max/10))

unset new_brightness
if [ "$dir" == "+" ] ; then
  new_brightness=$(($val+$ten_percent))
  if [ $new_brightness -gt $max ] ; then
    new_brightness=$max
  fi
  #notify-send "Brightness increased to $new_brightness"
elif [ "$dir" == "-" ] ; then
  new_brightness=$(($val-$ten_percent))
  if [ $new_brightness -lt 0 ] ; then
    new_brightness=0
  fi
  #notify-send "Brightness decreased to $new_brightness"
elif [ "$dir" == "default" ] ; then
  new_brightness=$default_brightness
  #notify-send "Brightness set to default value: $new_brightness"
fi

echo $new_brightness > /sys/class/backlight/intel_backlight/brightness

