#!/bin/bash

# Check if a file name is provided
if [ -z "$1" ]; then
	echo "No file name provided. Usage: pdftoclipboard filename.pdf"
	exit 1
fi

# Check if the file exists
if [ ! -f "$1" ]; then
	echo "File not found: $1"
	exit 1
fi

# Check if the file is a PDF
if [ ${1: -4} != ".pdf" ]; then
	echo "The file is not a PDF: $1"
	exit 1
fi

# Convert PDF to text and copy to clipboard
pdftotext "$@" - | xclip -selection clipboard

echo "Text copied to clipboard from file: $1"
