#!/bin/bash

declare -i ID
ID=$(xinput list | grep -E 'Synaptics\s*TM3330-001' | awk -F'id=' '{print $2}' | awk '{print $1}')
declare -i STATE
STATE=$(xinput list-props "$ID" | grep 'Device Enabled' | awk '{print $4}')
if [ "$STATE" -eq 1 ]
then
    xinput disable "$ID"
    # echo "Touchpad disabled."
    notify-send -a 'Touchpad' 'Touchpad Disabled' -i input-touchpad
else
    xinput enable "$ID"
    # echo "Touchpad enabled."
    notify-send -a 'Touchpad' 'Touchpad Enabled' -i input-touchpad
fi

